// frontend-angular/my-angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  items: any[] = [];
  newItemName: string = '';
  editItemId: number | null = null;
  editItemName: string = '';

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchItems();
  }

  fetchItems(): void {
    this.http.get<any[]>('http://localhost:3000/items')
      .subscribe(data => {
        this.items = data;
      });
  }

  addItem(): void {
    this.http.post('http://localhost:3000/items', { name: this.newItemName })
      .subscribe(() => {
        this.newItemName = '';
        this.fetchItems();
      });
  }

  updateItem(id: number): void {
    this.http.put(`http://localhost:3000/items/${id}`, { name: this.editItemName })
      .subscribe(() => {
        this.editItemId = null;
        this.editItemName = '';
        this.fetchItems();
      });
  }

  deleteItem(id: number): void {
    this.http.delete(`http://localhost:3000/items/${id}`)
      .subscribe(() => {
        this.fetchItems();
      });
  }

  setEditItem(item: any): void {
    this.editItemId = item.id;
    this.editItemName = item.name;
  }
}

<div>
  <h1>CRUD App with Angular</h1>
  <div>
    <input type="text" [(ngModel)]="newItemName" placeholder="New Item Name" />
    <button (click)="addItem()">Add Item</button>
  </div>
  <ul>
    <li *ngFor="let item of items">
      <ng-container *ngIf="editItemId === item.id; else showItemName">
        <input type="text" [(ngModel)]="editItemName" />
        <button (click)="updateItem(item.id)">Save</button>
      </ng-container>
      <ng-template #showItemName>
        {{ item.name }}
        <button (click)="setEditItem(item)">Edit</button>
      </ng-template>
      <button (click)="deleteItem(item.id)">Delete</button>
    </li>
  </ul>
</div>

// frontend-react/my-react-app/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [items, setItems] = useState([]);
  const [newItemName, setNewItemName] = useState('');
  const [editItemId, setEditItemId] = useState(null);
  const [editItemName, setEditItemName] = useState('');

  useEffect(() => {
    fetchItems();
  }, []);

  const fetchItems = async () => {
    const response = await fetch('http://localhost:3000/items');
    const data = await response.json();
    setItems(data);
  };

  const addItem = async () => {
    await fetch('http://localhost:3000/items', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ name: newItemName }),
    });
    setNewItemName('');
    fetchItems();
  };

  const updateItem = async (id) => {
    await fetch(`http://localhost:3000/items/${id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ name: editItemName }),
    });
    setEditItemId(null);
    setEditItemName('');
    fetchItems();
  };

  const deleteItem = async (id) => {
    await fetch(`http://localhost:3000/items/${id}`, {
      method: 'DELETE',
    });
    fetchItems();
  };

  return (
    <div className="App">
      <h1>CRUD App with React</h1>
      <div>
        <input
          type="text"
          value={newItemName}
          onChange={(e) => setNewItemName(e.target.value)}
          placeholder="New Item Name"
        />
        <button onClick={addItem}>Add Item</button>
      </div>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            {editItemId === item.id ? (
              <input
                type="text"
                value={editItemName}
                onChange={(e) => setEditItemName(e.target.value)}
              />
            ) : (
              item.name
            )}
            {editItemId === item.id ? (
              <button onClick={() => updateItem(item.id)}>Save</button>
            ) : (
              <button onClick={() => { setEditItemId(item.id); setEditItemName(item.name); }}>Edit</button>
            )}
            <button onClick={() => deleteItem(item.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
